## 1 Opening Csv File

In [3]:
import pandas as pd

In [5]:
df=pd.read_csv('InsuranceData.csv')

In [6]:
df

,PolicyNumber,CustomerID,Gender,Age,PolicyType,PolicyStartDate,PolicyEndDate,PremiumAmount,CoverageAmount,ClaimNumber,ClaimDate,ClaimAmount,ClaimStatus
0,P1,C1,Female,73,Auto,13-02-2024,13-02-2025,240.64,33175.10,C1,NaN,0.00,Rejected
1,P2,C2,Male,44,Travel,03-03-2024,03-03-2025,1059.73,85046.42,C2,22-06-2024,1493.06,Pending
2,P3,C3,Female,28,Travel,15-06-2024,15-06-2025,1019.59,68525.53,C3,NaN,0.00,Rejected
3,P4,C4,Male,85,Travel,03-06-2024,03-06-2025,549.70,17053.27,C4,25-02-2025,5021.34,Pending
4,P5,C5,Female,57,Travel,13-06-2024,13-06-2025,841.15,55007.27,C5,30-11-2024,1347.46,Pending
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9999,P10000,C10000,Male,44,Life,31-07-2023,31-07-2024,210.96,104709.99,C10000,10-04-2024,2092.75,Settled
10000,P1,C1,Female,73,Auto,13-02-2024,13-02-2025,240.64,33175.10,C1,NaN,0.00,Rejected
10001,P2,C2,Male,44,Travel,03-03-2024,03-03-2025,1059.73,85046.42,C2,22-06-2024,1493.06,Pending
10002,P2,C2,Male,44,Travel,03-03-2024,03-03-2025,1059.73,85046.42,C2,22-06-2024,1493.06,Pending
10003,P4,C4,Male,85,Travel,03-06-2024,03-06-2025,549.70,17053.27,C4,25-02-2025,5021.34,Pending

## 2  Opening Csv file From Url

In [9]:
import requests
import pandas as pd
from io import StringIO

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"

headers = {
    "User-Agent": "Mozilla/5.0",
    "Accept": "text/csv"
}

response = requests.get(url, headers=headers)

data=StringIO(response.text)

pd.read_csv(data)

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

 ## 3  Index_col Parameter

index_col="ID" → Uses the column named ID as the index.
index_col=0 → Uses the first column as the index.

In [8]:
df=pd.read_csv('InsuranceData.csv',index_col='PolicyNumber')
df

,CustomerID,Gender,Age,PolicyType,PolicyStartDate,PolicyEndDate,PremiumAmount,CoverageAmount,ClaimNumber,ClaimDate,ClaimAmount,ClaimStatus
PolicyNumber,,,,,,,,,,,,
P1,C1,Female,73,Auto,13-02-2024,13-02-2025,240.64,33175.10,C1,NaN,0.00,Rejected
P2,C2,Male,44,Travel,03-03-2024,03-03-2025,1059.73,85046.42,C2,22-06-2024,1493.06,Pending
P3,C3,Female,28,Travel,15-06-2024,15-06-2025,1019.59,68525.53,C3,NaN,0.00,Rejected
P4,C4,Male,85,Travel,03-06-2024,03-06-2025,549.70,17053.27,C4,25-02-2025,5021.34,Pending
P5,C5,Female,57,Travel,13-06-2024,13-06-2025,841.15,55007.27,C5,30-11-2024,1347.46,Pending
...,...,...,...,...,...,...,...,...,...,...,...,...
P10000,C10000,Male,44,Life,31-07-2023,31-07-2024,210.96,104709.99,C10000,10-04-2024,2092.75,Settled
P1,C1,Female,73,Auto,13-02-2024,13-02-2025,240.64,33175.10,C1,NaN,0.00,Rejected
P2,C2,Male,44,Travel,03-03-2024,03-03-2025,1059.73,85046.42,C2,22-06-2024,1493.06,Pending
P2,C2,Male,44,Travel,03-03-2024,03-03-2025,1059.73,85046.42,C2,22-06-2024,1493.06,Pending
P4,C4,Male,85,Travel,03-06-2024,03-06-2025,549.70,17053.27,C4,25-02-2025,5021.34,Pending

In [9]:
df=pd.read_csv('InsuranceData.csv',index_col=0)
df

,CustomerID,Gender,Age,PolicyType,PolicyStartDate,PolicyEndDate,PremiumAmount,CoverageAmount,ClaimNumber,ClaimDate,ClaimAmount,ClaimStatus
PolicyNumber,,,,,,,,,,,,
P1,C1,Female,73,Auto,13-02-2024,13-02-2025,240.64,33175.10,C1,NaN,0.00,Rejected
P2,C2,Male,44,Travel,03-03-2024,03-03-2025,1059.73,85046.42,C2,22-06-2024,1493.06,Pending
P3,C3,Female,28,Travel,15-06-2024,15-06-2025,1019.59,68525.53,C3,NaN,0.00,Rejected
P4,C4,Male,85,Travel,03-06-2024,03-06-2025,549.70,17053.27,C4,25-02-2025,5021.34,Pending
P5,C5,Female,57,Travel,13-06-2024,13-06-2025,841.15,55007.27,C5,30-11-2024,1347.46,Pending
...,...,...,...,...,...,...,...,...,...,...,...,...
P10000,C10000,Male,44,Life,31-07-2023,31-07-2024,210.96,104709.99,C10000,10-04-2024,2092.75,Settled
P1,C1,Female,73,Auto,13-02-2024,13-02-2025,240.64,33175.10,C1,NaN,0.00,Rejected
P2,C2,Male,44,Travel,03-03-2024,03-03-2025,1059.73,85046.42,C2,22-06-2024,1493.06,Pending
P2,C2,Male,44,Travel,03-03-2024,03-03-2025,1059.73,85046.42,C2,22-06-2024,1493.06,Pending
P4,C4,Male,85,Travel,03-06-2024,03-06-2025,549.70,17053.27,C4,25-02-2025,5021.34,Pending

## 4 Header Parameter

The header parameter in pd.read_csv() specifies which row contains the column names.
1 Default: header=0
Pandas assumes the first row contains column names.
2 header=None
Use this when the file does not have column names.
3. header=1
Use the second row as column names.
4. Custom Column Names
df = pd.read_csv(
    "data.csv",
    header=None,
    names=["Student_ID", "Student_Name", "Student_Age"]
)

## 5 use_cols Parameter

The usecols parameter is used in pd.read_csv() to load only specific columns from a CSV file.

In [17]:
df=pd.read_csv('InsuranceData.csv',usecols=["CustomerID","Gender","Age","ClaimAmount"],index_col=0)
df

            Gender  Age  ClaimAmount
CustomerID
C1          Female   73         0.00
C2            Male   44      1493.06
C3          Female   28         0.00
C4            Male   85      5021.34
C5          Female   57      1347.46
...            ...  ...          ...
C10000        Male   44      2092.75
C1          Female   73         0.00
C2            Male   44      1493.06
C2            Male   44      1493.06
C4            Male   85      5021.34

[10004 rows x 3 columns]