In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
date=pd.read_csv('orders.csv')
time=pd.read_csv('messages.csv')

In [4]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [5]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [6]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [7]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

# Working With Dates

In [8]:
# Converting to datetime datatype
date['date']=pd.to_datetime(date['date'])

In [9]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

## 1.  Extract Year

In [10]:
date['date_year']=date['date'].dt.year

date.sample(5)

          date  product_id  city_id  orders  date_year
321 2019-12-04        2981       26     461       2019
284 2018-07-27        3635       16      48       2018
950 2019-05-10        2137        2      10       2019
883 2019-12-04        7223        2      15       2019
909 2018-10-10        3965        9       1       2018

## 2. Extract Month

In [11]:
date['date_month_no']=date['date'].dt.month

date.head()

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8
2 2018-10-23        1859       25       1       2018             10
3 2019-08-17        7292       25       1       2019              8
4 2019-01-06        4344       25       3       2019              1

In [12]:
date['date_month_name']=date['date'].dt.month_name()

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

## Extract Days

In [13]:
date['date_day']=date['date'].dt.day
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [14]:
## day of week

date['day_of_week']=date['date'].dt.dayofweek
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,day_of_week
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [15]:
## day of week -name
date['date_dow_name']=date['date'].dt.day_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,day_of_week,date_dow_name
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday

In [16]:
date.drop(columns=['product_id','city_id','orders'])

,date,date_year,date_month_no,date_month_name,date_day,day_of_week,date_dow_name
0,2019-12-10,2019,12,December,10,1,Tuesday
1,2018-08-15,2018,8,August,15,2,Wednesday
2,2018-10-23,2018,10,October,23,1,Tuesday
3,2019-08-17,2019,8,August,17,5,Saturday
4,2019-01-06,2019,1,January,6,6,Sunday
...,...,...,...,...,...,...,...
995,2018-10-08,2018,10,October,8,0,Monday
996,2018-12-06,2018,12,December,6,3,Thursday
997,2019-05-07,2019,5,May,7,1,Tuesday
998,2019-03-03,2019,3,March,3,6,Sunday
999,2019-10-15,2019,10,October,15,1,Tuesday

In [17]:
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,day_of_week,date_dow_name
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday

In [18]:
# is weekend ?

date['date_is_weekend']=np.where(date['date_dow_name'].isin(['Sunday','Saturday']),1,0)

In [19]:
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,day_of_week,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

## Extract week of the year

In [20]:
date['date_week'] = date['date'].dt.isocalendar().week

In [21]:
date.drop(columns=['product_id','city_id','orders'])

,date,date_year,date_month_no,date_month_name,date_day,day_of_week,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,2019,1,January,6,6,Sunday,1,1
...,...,...,...,...,...,...,...,...,...
995,2018-10-08,2018,10,October,8,0,Monday,0,41
996,2018-12-06,2018,12,December,6,3,Thursday,0,49
997,2019-05-07,2019,5,May,7,1,Tuesday,0,19
998,2019-03-03,2019,3,March,3,6,Sunday,1,9
999,2019-10-15,2019,10,October,15,1,Tuesday,0,42

## Extract Quarter

In [24]:
date['quarter']=date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,day_of_week,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

## Extract Semester

In [26]:
date['semester']=np.where(date['quarter'].isin([1,2]),1,2)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,day_of_week,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1,1

## Extract Time elapsed between dates

In [27]:
import datetime

today=datetime.datetime.today()

today

datetime.datetime(2026, 7, 17, 7, 38, 20, 579777)

In [28]:
today-date['date']

0     2411 days 07:38:20.579777
1     2893 days 07:38:20.579777
2     2824 days 07:38:20.579777
3     2526 days 07:38:20.579777
4     2749 days 07:38:20.579777
                 ...
995   2839 days 07:38:20.579777
996   2780 days 07:38:20.579777
997   2628 days 07:38:20.579777
998   2693 days 07:38:20.579777
999   2467 days 07:38:20.579777
Name: date, Length: 1000, dtype: timedelta64[ns]

In [29]:
(today-date['date']).dt.days

0      2411
1      2893
2      2824
3      2526
4      2749
       ...
995    2839
996    2780
997    2628
998    2693
999    2467
Name: date, Length: 1000, dtype: int64

In [33]:
## Month Passed

np.round((today-date['date'])/np.timedelta64(3044,'m'),0)

0      1141.0
1      1369.0
2      1336.0
3      1195.0
4      1301.0
        ...
995    1343.0
996    1315.0
997    1243.0
998    1274.0
999    1167.0
Name: date, Length: 1000, dtype: float64

In [34]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [35]:
## converting to date time data type

time['date']=pd.to_datetime(time['date'])

In [36]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [38]:
time['hour']=time['date'].dt.hour
time['min']=time['date'].dt.minute
time['sec']=time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

## Extract Time part

In [39]:
time['time']=time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

## Time Difference

In [40]:
today-time['date']

0     4597 days 06:48:20.579777
1     4461 days 07:58:20.579777
2     4947 days 07:17:20.579777
3     4249 days 07:07:20.579777
4     4646 days 08:27:20.579777
                 ...
995   5236 days 06:48:20.579777
996   4557 days 08:24:20.579777
997   5022 days 08:01:20.579777
998   5138 days 08:04:20.579777
999   4410 days 08:13:20.579777
Name: date, Length: 1000, dtype: timedelta64[ns]

In [41]:
## in minute

(today-time['date'])/np.timedelta64(1,'s')

0      3.972053e+08
1      3.854591e+08
2      4.274470e+08
3      3.671392e+08
4      4.014448e+08
           ...
995    4.524149e+08
996    3.937551e+08
997    4.339297e+08
998    4.439523e+08
999    3.810536e+08
Name: date, Length: 1000, dtype: float64

In [ ]:
(today-time['date'])/np.timedelta6